using System;
using System.Collections.Generic;

namespace DcProcurement.Contexts
{
    public partial class Stafftab
    {
        public decimal RecordId { get; set; }
        public string Staffid { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Othernames { get; set; }
        public string Initials { get; set; }
        public string Deptcode { get; set; }
        public string Gradelvl { get; set; }
        public decimal? Paystatus { get; set; }
        public decimal? Stafftype { get; set; }
        public bool? Taxable { get; set; }
        public string Accountid { get; set; }
        public bool? Overtime { get; set; }
        public string Taxregion { get; set; }
        public bool? Union1 { get; set; }
        public string Bankid { get; set; }
        public bool? Suspended { get; set; }
        public string Positionid { get; set; }
        public string Title { get; set; }
        public decimal? Sex { get; set; }
        public decimal? Children { get; set; }
        public decimal? Relatives { get; set; }
        public string Housecode { get; set; }
        public decimal? Paywhen { get; set; }
        public bool? Disable { get; set; }
        public decimal? Lastpay { get; set; }
        public decimal? Status { get; set; }
        public decimal? Freemethod { get; set; }
        public string Office { get; set; }
        public string Suboffice { get; set; }
        public decimal? Subaccount { get; set; }
        public bool? Rentad { get; set; }
        public string Cc { get; set; }
        public string Picpath { get; set; }
        public string Compcode { get; set; }
        public string Email { get; set; }
        public string Natidno { get; set; }
        public decimal? Percent2 { get; set; }
        public DateTime? Effedate { get; set; }
        public decimal? Effewdays { get; set; }
        public decimal? Penrate { get; set; }
        public bool? Pensionable { get; set; }
        public bool? Nsitf1 { get; set; }
        public decimal? Oldval { get; set; }
        public bool? Promoted { get; set; }
        public bool? Nhf { get; set; }
        public decimal? Peneffewdays { get; set; }
        public bool? Penongross { get; set; }
        public bool? Promoted2 { get; set; }
        public bool? Dayw { get; set; }
        public string Susstatus { get; set; }
        public DateTime? Pdate { get; set; }
        public DateTime? Tdate { get; set; }
        public DateTime? Djoin { get; set; }
        public decimal? Bonus { get; set; }
        public string Sreason { get; set; }
        public string Cat2 { get; set; }
        public string Terminate { get; set; }
        public decimal? Ovtcum { get; set; }
        public bool? Cessation { get; set; }
        public DateTime? Cesdate { get; set; }
        public DateTime? Dpromoted { get; set; }
        public string Taxref { get; set; }
        public string Pfa { get; set; }
        public DateTime? Pendate { get; set; }
        public decimal? Penwdays { get; set; }
        public string Country { get; set; }
        public decimal? Amtdue { get; set; }
        public DateTime? Suspdate { get; set; }
        public decimal? Suspperm { get; set; }
        public decimal? Perovt { get; set; }
        public bool? Fmark { get; set; }
        public string BloodGrp { get; set; }
        public string Gynotype { get; set; }
        public string EyeColor { get; set; }
        public decimal? Height { get; set; }
        public string Haircolor { get; set; }
        public DateTime? Dtengaged { get; set; }
        public string Tumbpic { get; set; }
        public string Signpic { get; set; }
        public decimal? EntryYrExp { get; set; }
        public DateTime? Dpromo { get; set; }
        public decimal? BSalary { get; set; }
        public decimal? Amtduebal { get; set; }
        public bool? Testadmin { get; set; }
        public string Cardno { get; set; }
        public string Posting { get; set; }
        public string Nysccdno { get; set; }
        public string Nysccdday { get; set; }
        public string Nysccdgroup { get; set; }
        public bool? Pleave { get; set; }
        public bool? Cstaff { get; set; }
        public string Scodee { get; set; }
        public bool? Bar1 { get; set; }
        public bool? Ppay { get; set; }
        public string Btype { get; set; }
        public bool? Indu { get; set; }
        public string Rsapin { get; set; }
        public string Cadre { get; set; }
        public string Accountid1 { get; set; }
        public string Acctype { get; set; }
        public string Bankcode1 { get; set; }
        public string Branchcode1 { get; set; }
        public byte[] Picimg { get; set; }
        public string Pictype { get; set; }
        public byte[] Thbimg { get; set; }
        public string Thbtype { get; set; }
        public byte[] Sigimg { get; set; }
        public string Sigtype { get; set; }
        public string Ethnicity { get; set; }
        public string Bankbvn { get; set; }
        public bool? Psal { get; set; }
        public int? Pwhen { get; set; }
        public bool? Newstaff { get; set; }
        public int? Losyears { get; set; }
        public int? Losmonths { get; set; }
        public int? Losdays { get; set; }
        public int? Lostotal { get; set; }
        public string BankAcType { get; set; }
        public string BankSwitchCode { get; set; }
        public bool? Excldfrmbudget { get; set; }
        public string Sen { get; set; }
        public string Fed { get; set; }
        public string Sed { get; set; }
    }
}
